version: '3'

services:
  init-nginx:
    init_container: true
    image: nginx
    container_name: init-nginx
    restart: always
    ports:
      - "80"


  nginx2:
    image: nginx:alpine
    container_name: nginx-service2
    restart: always
    ports:
      - "80"

  nginx3:
    image: nginx:alpine
    container_name: nginx-service3
    restart: always
    ports:
      - "80"
