version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-service
    restart: always
    ports:
      - "8888:80"


  nginx2:
    image: nginx:alpine
    container_name: nginx-service2
    restart: always
    ports:
      - "8889:80"
